### ISSUE TITLE
Vote counting bug?

### ISSUE THREAD

**Issue by hongaar** [Chaosthebot/Chaos#142]
#106 got two votes according to the chaosbot while it should have had 18 (17 👍 plus PR owners vote): 

> 🙆 PR passed with a vote of 2 for and 0 against, with a weighted total of 1.2 and a threshold of 1.0.

https://github.com/chaosbot/chaos/commit/d2d455a10cfc4b0de1ff533d9573e42be6489067

> 👍 17

https://github.com/chaosbot/chaos/pull/106

**Comment by amoffat** [comment]
before #117 was merged in, only votes that were made after the branch's repo was last updated were counted.  so for example, if you opened #106, collected some votes, then made changes to your branch *or any branch attached to your downstream,* chaosbot would ignore all votes on any of your PRs made after your change.  so if you did any of these things, that would explain it.

the core reason for this was we had no way of getting the last update time of an individual branch, only the entire repo, to use for comparisons with the vote times (to ensure that people knew what they were voting on).

anyways, since #117 was merged, the discrepancy should be gone, since we don't care about vote times anymore

**Comment by hongaar** [comment]
Ah!

I was _just_ about to make a new issue for this code:

```python
def get_pr_last_updated(pr_data):
    """ a helper for finding the utc datetime of the last pr branch
    modifications """
    repo = pr_data["head"]["repo"]
    if repo:
        dt = repo["pushed_at"]
    else:
        dt = pr_data["created_at"]
    return arrow.get(dt)
```

Because it seemed like there's a bug and figured it should instead use the commit info to fetch the created/pushed_at date (i.e. using https://developer.github.com/v3/git/commits/#get-a-commit)

**Comment by amoffat** [comment]
@hongaar the way it's currently working is still less than ideal, so if you can get more accurate info from the latest commit, we should definitely try for that.  My understanding though is that commit data is easily forgable (see [here](https://github.com/amoffat/masquerade)) so I'm not sure if the info that comes back from the api is derived from the commit, from github, or both?  We may only be able to rely on it if it comes from github
