### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by rudehn** [Chaosthebot/Chaos#241]
Can we test code changes before submitting a PR? Some of these errors would be caught simply by trying to run the bot...

**Comment by g19fanatic** [comment]
The current dockerfile doesn't really work well. I'm currently attempting to get this working. I'll push a PR when its done(if someone doesn't beat me to it)

**Comment by g19fanatic** [comment]
Since the process is currently being 'handled' by an outside supervisord (and that not being configured by the project itself), the dockerfile won't be an exact environment as is currently installed. This could be 'fixed' by setting up supervisord w/ puppet. But i do not know if thats desired.

The initial setup of the VPS (supervisor and mysql) would need to be coordinated w/ @amoffat

**Comment by g19fanatic** [comment]
Well maybe... i can duplicate the environment in the docker isntance... I'll go that route for right now. I can PR it later on so that chaosbot controls supervisor and mysql...

**Comment by rudehn** [comment]
Getting started with mysql integration would be an interesting challenge haha
