### ISSUE TITLE
[frontend-ninjas] js background bug on high resolution

### ISSUE THREAD

**Issue by flibustier** [Chaosthebot/Chaos#482]
The page does not respond, because of chaos.js according to Firefox
![image](https://cloud.githubusercontent.com/assets/9994935/26727242/5b153a06-47a6-11e7-8bf1-f173e313e167.png)

> Line 22 in chaos.js

Firefox on Windows 10 2736*1824 (because 1080p is for the weak!)

**Comment by qgustavor** [comment]
I tried emulating the same resolution in Firefox and it worked without problems:

![cropped screenshot](https://i.imgur.com/DTqmWpl.png)

~~I think the problem is the high DPI, not the high resolution. I couldn't find an option to emulate high DPI screens in Firefox. I tested the page in Chrome with an emulated high DPI screen and it worked, so I think Firefox that's buggy.~~ [I found a way to emulate high DPI screens](https://stackoverflow.com/a/17228026) and I still couldn't reproduce the issue. Maybe it's the Firefox version: I tested on Firefox Mobile Beta 49.0b6, Firefox Developer 54.0b12 and Firefox 45 on Windows (via browserling).

I don't want to touch a JavaScript file with 4 space indentations and double quotes (*I prefer the chaos*). Anyway, maybe replacing `canvas.width` and `canvas.height` with constants will fix it.

**Comment by flibustier** [comment]
Same issue on Firefox ESR on Linux (Debian) with 1080p 15,7" 
![capture du 2017-06-02 18-02-56](https://cloud.githubusercontent.com/assets/9994935/26734349/f1ff7366-47bd-11e7-9639-0cdfacc42147.png)

**Comment by o3LL** [comment]
@md678685 @Leigende

**Comment by Alexays** [comment]
I can't reproduce the bug even emulating the resolution :(

**Comment by mdcfe** [comment]
@MUCHZER I didn't write the actual animation - no idea what happened there. I'm also not a canvas expert, and unfortunately I don't use Firefox nor do I have access to a high DPI screen 😕

**Comment by PlasmaPower** [comment]
The solution is instead of hardcoding 2x2 pixel blocks, use the DPI to figure out how large the blocks should be.

**Comment by PlasmaPower** [comment]
I'll make a PR.
